- contracts/ValidatorMetadata.sol
- scripts/test-poa-setup.js
- test/metadata_test.js
Fix an issue in ValidatorMetadata from double changing metadata having the same confirmations.
Solution: Reset confirmation when changeRequest is called
> Fix an issue in ValidatorMetadata

- contracts/KeysManager.sol
- contracts/PoaNetworkConsensus.sol
- contracts/ProxyStorage.sol
- test/ballots_storage_test.js
- test/keys_manager_test.js
- test/metadata_test.js
- test/mockContracts/KeysManagerMock.sol
- test/mockContracts/PoaNetworkConsensusMock.sol
- test/mockContracts/ProxyStorageMock.sol
- test/poa_network_consensus_test.js
- test/proxy_storage_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_proxy_test.js
In order to use multiset feature from parity, we have to be able to
1. Set ProxyStorage via constructor
2. Set Previous Set of Validators
> (Feature) Allow PoA contract to handle hard forks

- contracts/KeysManager.sol
- contracts/interfaces/IKeysManager.sol
- contracts/interfaces/IProxyStorage.sol
- migrations/2_deploy_contract.js
- test/keys_manager_test.js
1. Change IF to `require` for error handling
2. Split 1 method into 2 `migrateInitialKey` and `migrateMiningKey` 
3. Add event Migrate
> (Improvement) Split migration method into 2 separate method and event

- contracts/KeysManager.sol
- test/keys_manager_test.js
Fixes #36 
Previously, swapping mining key would not carry over voting and payout keys as it should
> (Fix) Swap mining keys copies voting and payout over

- contracts/KeysManager.sol
- contracts/PoaNetworkConsensus.sol
- contracts/interfaces/IPoaNetworkConsensus.sol
- migrations/2_deploy_contract.js
- test/ballots_storage_test.js
- test/helpers.js
- test/poa_network_consensus_test.js
- truffle.js
Previously, we had an issue with double emitting of IntializeChange event due to reusing add/remove methods for mining swap.
In this PR, we implement independent method to make a swap in PoA, and add necessary changes to KeysManager
> Fix swap mining keys

- scripts/getABI.js
Script to generate multi-line ABIs of contracts.
Run: `node getABI.js` from scripts folder after contracts are compiled with truffle. 
It generates multi-line ABIs of contracts to the `build/contracts` folder
> (Feature) script to generate multi-line ABIs of contracts

- scripts/getABI.js
**Problem**: If no `OUTPUT` env variable, script generates files in `build` folder with name `abisKeysManager.json`...
**Solution**: Add trailing slash for default folder
> (Fix) Default folder trailing slash for getABI.js script

- .gitignore
- migrations/2_deploy_contract.js
Adds ability to save secondary contracts addresses to the `.json` file from test deployment script with `SAVE_TO_FILE=true` env variable. It is useful for quick POA setup deployment I'm working under.
> (Feature) deployment-script: save to file contracts' addresses

- README.md
- scripts/poa-bytecode.js
There is a wrong manual in `README` about how to get a bytecode of `PoaNetworkConsensus` contract. It doesn't take into account that the bytecode must contain constructor parameters. I have corrected the `README` and have made a small script to generate the bytecode of `PoaNetworkConsensus`.
(Fix)
> (Fix) README text about PoaNetworkConsensus bytecode

- contracts/BlockReward.sol
- contracts/interfaces/IBlockReward.sol
Adding `BlockReward` contract to `security-audit` branch. Relates to https://github.com/poanetwork/RFC/issues/14.
(Feature)
> (Feature) Add BlockReward contract to security-audit branch

- contracts/KeysManager.sol
- contracts/VotingToChangeKeys.sol
- contracts/interfaces/IKeysManager.sol
- test/keys_manager_test.js
- test/keys_manager_upgrade_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
Changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/92, https://github.com/poanetwork/poa-network-consensus-contracts/issues/117 and https://github.com/poanetwork/poa-dapps-voting/issues/83.
(Feature)
> (Feature) Add new validator with mining/voting/payout keys at once

- test/ballots_storage_test.js
- test/ballots_storage_upgrade_test.js
- test/emission_funds_test.js
- test/eternal_storage_proxy_test.js
- test/keys_manager_test.js
- test/keys_manager_upgrade_test.js
- test/metadata_test.js
- test/metadata_upgrade_test.js
- test/mockContracts/KeysManagerMock.sol
- test/poa_network_consensus_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_min_threshold_upgrade_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
- test/voting_to_manage_emission_funds_test.js
- test/voting_to_manage_emission_funds_upgrade_test.js
Unit tests didn't fully cover smart contracts as it was mentioned in https://github.com/poanetwork/poa-network-consensus-contracts/issues/114. Now all tests are extended.
Use `npm run coverage` to see an actual `solidity-coverage` report:
**(Mandatory) What is it: (Fix), (Feature) or (Refactor)**
(Feature)
> (Feature) Extend missed unit tests

- contracts/ValidatorMetadata.sol
- contracts/VotingToChangeKeys.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/VotingToManageEmissionFunds.sol
This PR is a part of `Voting DApp` optimization. It adds `ValidatorMetadata.getValidatorName` and `VotingTo*.getBallotInfo` getters to make `Voting DApp` be able to read ballot's data from new smart contracts in a single request.
(Feature)
> (Feature) Add extra getters for Voting DApp optimization

- contracts/VotingToChangeKeys.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/abstracts/VotingToChange.sol
This PR fixes "Stack too deep" compilation error in the new `VotingToChangeKeys.getBallotInfo` getter that was added in #129.
(Fix)
> (Fix) "Stack too deep" error in VotingToChangeKeys.getBallotInfo

- contracts/BlockReward.sol
- test/block_reward_test.js
- test/mockContracts/BlockRewardMock.sol
- test/utils/helpers.js
These changes complement `BlockReward` contract by `rewardHBBFT` function that implements the logic described in https://github.com/poanetwork/RFC/issues/16. Also, some unit tests were added to `test/block_reward_test.js` to check that logic. The `rewardHBBFT` function must be called by HBBFT engine (https://github.com/poanetwork/hbbft) when creating each block.
(Feature)
> (Feature) Block Reward emission by time

- README.md
- contracts/ProxyStorage.sol
- contracts/interfaces/IProxyStorage.sol
- migrations/2_deploy_contract.js
- scripts/migrate/migrateAll.js
- test/ballots_storage_test.js
- test/ballots_storage_upgrade_test.js
- test/keys_manager_test.js
- test/keys_manager_upgrade_test.js
- test/metadata_test.js
- test/metadata_upgrade_test.js
- test/poa_network_consensus_test.js
- test/proxy_storage_test.js
- test/proxy_storage_upgrade_test.js
- test/reward_by_block_test.js
- test/reward_by_block_upgrade_test.js
- test/reward_by_time_test.js
- test/reward_by_time_upgrade_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_min_threshold_upgrade_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
- test/voting_to_manage_emission_funds_test.js
- test/voting_to_manage_emission_funds_upgrade_test.js
`ProxyStorage` contract has been supplemented to be able to store the addresses of `RewardByBlock` and `VotingToManageEmissionFunds` contracts (addresses of their eternal storages) which contain logic described for `Increased Emission Supply` in https://github.com/poanetwork/RFC/issues/14. However, `ProxyStorage.setContractAddress` function still doesn't allow to change implementations of these contracts because it is supposed to add this feature later, when necessary, by upgrading ProxyStorage's implementation (validators will be able to do that with `VotingToChangeProxyAddress`).
(Fix)
> (Fix) Add keeping of RewardByBlock and VotingToManageEmissionFunds addresses to ProxyStorage

- contracts/BallotsStorage.sol
- contracts/ValidatorMetadata.sol
- contracts/abstracts/VotingToChange.sol
BallotsStorage.sol:
- `getBallotLimitPerValidator` function now returns `1` instead of `0` if the number of validators is more than `200`
ValidatorMetadata.sol:
- `MAX_PENDING_CHANGE_CONFIRMATIONS` constant was removed
- `changeRequestForValidator` function was removed
VotingToChange.sol:
- wrong inequality was fixed in `withinLimit` function
**(Mandatory) What is it: (Fix), (Feature) or (Refactor)**
(Fix)
> (Fix) BallotsStorage.sol, ValidatorMetadata.sol and VotingToChange.sol

- contracts/VotingToChangeKeys.sol
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
`VotingToChangeKeys` contract allows creating a ballot for adding voting/ payout key with 0x0 mining key (see `VotingToChangeKey.areBallotParamsValid` function). Corresponding issue: https://github.com/poanetwork/poa-dapps-voting/issues/161. This PR fixes that.
(Fix)
> (Fix) Don't allow adding voting/ payout key for zero mining key

- contracts/KeysManager.sol
- contracts/interfaces/IKeysManager.sol
- scripts/migrate/migrateKeys.js
- test/keys_manager_test.js
- test/keys_manager_upgrade_test.js
- test/mockContracts/KeysManagerMock.sol
This PR removes `KeysManager.initialKeys` and `KeysManager.getInitialKey` functions and adds `KeysManager.getInitialKeyStatus` function as it is suggested by MixBytes audit team.
(Refactor)
> (Refactor) Add KeysManager.getInitialKeyStatus function instead of initialKeys and getInitialKey

- contracts/ValidatorMetadata.sol
- test/metadata_test.js
- test/metadata_upgrade_test.js
This PR removes the functions from `ValidatorMetadata` related to changing ProxyStorage's address. Those functions are no longer needed in `ValidatorMetadata` because now we have the upgradable `ProxyStorage`.
(Fix)
> (Fix) Remove changing of ProxyStorage's address from ValidatorMetadata

- contracts/KeysManager.sol
- contracts/eternal-storage/EternalStorageProxy.sol
- test/eternal_storage_proxy_test.js
- truffle.js
- `KeysManager.createKeys` function has been complemented with `withinTotalLimit` modifier.
- `EternalStorageProxy.upgradeTo` function now doesn't revert if a new implementation address is the same as a previous.
- Gas limit has been increased to 6400000 for `sokol` network in `truffle.js` to successfully deploy `KeysManager` and `VotingToChangeKeys` contracts with `migrations/2_deploy_contract.js` script.
(Fix)
> (Fix) Small fixes of KeysManager and EternalStorageProxy contracts

- contracts/KeysManager.sol
- contracts/PoaNetworkConsensus.sol
- contracts/interfaces/IKeysManager.sol
- scripts/migrate/migrateAll.js
- scripts/migrate/migrateKeys.js
- test/keys_manager_test.js
- test/keys_manager_upgrade_test.js
- test/mockContracts/PoaNetworkConsensusMock.sol
- test/poa_network_consensus_test.js
- `PoaNetworkConsensus` constructor has been complemented with checking for keys duplication. 
- `PoaNetworkConsensus.isMasterOfCeremonyInitialized` boolean flag has been renamed to `wasProxyStorageSet`.
- `KeysManager.migrateMiningKey` function now uses `maxOldMiningKeysDeepCheck()` public getter instead of `_maxMiningKeyHistoryDeep` parameter.
(Fix)
> (Fix) PoaNetworkConsensus contract and KeysManager.migrateMiningKey function

- contracts/KeysManager.sol
- contracts/ValidatorMetadata.sol
- contracts/interfaces/IProxyStorage.sol
- contracts/interfaces/IValidatorMetadata.sol
- test/ballots_storage_test.js
- test/ballots_storage_upgrade_test.js
- test/keys_manager_test.js
- test/keys_manager_upgrade_test.js
- test/metadata_test.js
- test/metadata_upgrade_test.js
- test/reward_by_block_test.js
- test/reward_by_block_upgrade_test.js
- test/reward_by_time_test.js
- test/reward_by_time_upgrade_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_min_threshold_upgrade_test.js
`ValidatorMetadata` contract has been complemented by `moveMetadata` and `clearMetadata` external functions that can only be called by `KeysManager` contract.
`moveMetadata` function is called by `KeysManager.swapMiningKey` function to keep metadata of validator when his mining key is swapped.
`clearMetadata` function is called by `KeysManager.removeMiningKey` function to clear metadata of validator when his mining key is removed.
(Fix)
> (Fix) Add moveMetadata and clearMetadata functions to ValidatorMetadata contract

- contracts/BallotsStorage.sol
- contracts/KeysManager.sol
- contracts/RewardByBlock.sol
- contracts/ValidatorMetadata.sol
- contracts/VotingToChangeKeys.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/VotingToManageEmissionFunds.sol
- contracts/abstracts/VotingTo.sol
- contracts/abstracts/VotingToChange.sol
`abi.encodePacked` function has been replaced with `abi.encode` to make bytes sequences for `keccak256` more unique and to reduce hash collision probability.
(Fix)
> (Fix) Replace abi.encodePacked with abi.encode

- contracts/VotingToManageEmissionFunds.sol
- test/voting_to_manage_emission_funds_test.js
- test/voting_to_manage_emission_funds_upgrade_test.js
`VotingToManageEmissionFunds` contract now will use `BallotsStorage.getProxyThreshold` function instead of `BallotsStorage.getBallotThreshold`. It means that more than half of the validators must give their votes in order for ballot's changes to come into force (funds would be sent or burnt).
(Fix)
> (Fix) Using of BallotsStorage.getProxyThreshold in VotingToManageEmissionFunds

- contracts/BallotsStorage.sol
- contracts/KeysManager.sol
- contracts/ValidatorMetadata.sol
- contracts/VotingToChangeKeys.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/VotingToManageEmissionFunds.sol
- contracts/abstracts/VotingTo.sol
- contracts/abstracts/VotingToChange.sol
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
Some private functions had been returning an address of contract instead of an interface. For example:
```
function _getBallotsStorage() internal view returns(address) {
return IProxyStorage(proxyStorage()).getBallotsStorage();
}
```
Returning of address was replaced with returning of interface for the above cases to make the code more type-safe:
```
function _getBallotsStorage() internal view returns(IBallotsStorage) {
return IBallotsStorage(IProxyStorage(proxyStorage()).getBallotsStorage());
}
```
(Refactor)
> (Refactor) Replace returns(address) with returns(interface) in several private functions

- contracts/eternal-storage/EternalStorage.sol
- contracts/eternal-storage/EternalStorageProxy.sol
- test/ballots_storage_test.js
- test/emission_funds_test.js
- test/keys_manager_test.js
- test/metadata_test.js
- test/proxy_storage_test.js
- test/proxy_storage_upgrade_test.js
- test/reward_by_block_test.js
- test/reward_by_block_upgrade_test.js
- test/reward_by_time_test.js
- test/reward_by_time_upgrade_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
- test/voting_to_manage_emission_funds_test.js
`implementation` and `version` functions have been moved from `EternalStorage` to `EternalStorageProxy` contract. Thus, they are removed from implementations and available only in `EternalStorageProxy`.
(Refactor)
> (Refactor) Move `implementation` and `version` functions from `EternalStorage` to `EternalStorageProxy`

- contracts/ValidatorMetadata.sol
- contracts/eternal-storage/EternalStorageProxy.sol
- test/metadata_test.js
- test/metadata_upgrade_test.js
`ValidatorMetadata.moveMetadata` and `ValidatorMetadata.clearMetadata` functions now take into account pending confirmations if they are existed: `moveMetadata` moves confirmations from an old mining key to a new mining key, `clearMetadata` removes confirmations for a specified mining key.
(Fix)
> (Fix) Accounting of pending confirmations in ValidatorMetadata's `moveMetadata` and `clearMetadata` functions

- contracts/VotingToManageEmissionFunds.sol
- test/utilContracts/VotingKey.sol
- test/voting_to_manage_emission_funds_test.js
- test/voting_to_manage_emission_funds_upgrade_test.js
`VotingToManageEmissionFunds._finalize` private function has been complemented with checking whether a voting key is an EOA (externally owned account) or a contract. This is necessary to prevent stack overflow when a ballot is being finalized and when `EmissionFunds` functions are consequently being called. `extcodesize` opcode is used for this checking:
```
function _isEOA(address addr) internal view returns (bool) {
uint256 size;
assembly { size := extcodesize(addr) }
return size == 0;
}
```
(Feature)
> (Feature) Checking if a voting key is EOA or a contract

- README.md
- contracts/VotingToManageEmissionFunds.sol
- contracts/abstracts/VotingTo.sol
- contracts/abstracts/VotingToChange.sol
- migrations/2_deploy_contract.js
- scripts/migrate/migrateVotings.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_min_threshold_upgrade_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
Now voting and finalization functions of `VotingToChange*` contracts cannot be called until `migrateDisable` function is called.
(Fix)
> (Fix) Deny using VotingToChange* functions unless migration is completed

- contracts/VotingToChangeKeys.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/abstracts/VotingToChange.sol
- contracts/interfaces/IVotingToChangeKeys.sol
- contracts/interfaces/IVotingToChangeMinThreshold.sol
- contracts/interfaces/IVotingToChangeProxyAddress.sol
- package-lock.json
- scripts/migrate/migrateVotings.js
- scripts/test.sh
- test/mockContracts/VotingToChangeKeysMock.sol
- test/mockContracts/VotingToChangeMinThresholdMock.sol
- test/mockContracts/VotingToChangeProxyAddressMock.sol
- test/upgradeContracts/VotingToChangeKeysNew.sol
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_min_threshold_upgrade_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
The function `migrateBasicOne` in `VotingToChange*` contracts has been made safer: now it doesn't allow the contract owner to change some ballot info during migration from old contract to the new one.
(Fix)
> (Fix) Security enhancements of `VotingToChange*.migrateBasicOne` function

- contracts/KeysManager.sol
- contracts/PoaNetworkConsensus.sol
- test/poa_network_consensus_test.js
Some small enhancements in the code of `KeysManager` and `PoaNetworkConsensus` contracts. Now `PoaNetworkConsensus.setProxyStorage` function can only be called by MoC or by contract's owner.
(Fix)
> (Fix) Minor improvements of KeysManager and PoaNetworkConsensus.setProxyStorage

- contracts/BallotsStorage.sol
- contracts/KeysManager.sol
- contracts/ProxyStorage.sol
- contracts/ValidatorMetadata.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/VotingToManageEmissionFunds.sol
- contracts/abstracts/VotingTo.sol
- contracts/abstracts/VotingToChange.sol
- contracts/interfaces/IBallotsStorage.sol
- contracts/interfaces/IKeysManager.sol
- test/ballots_storage_upgrade_test.js
- test/mockContracts/BallotsStorageMock.sol
- test/mockContracts/KeysManagerMock.sol
- test/mockContracts/VotingToChangeKeysMock.sol
- test/mockContracts/VotingToChangeMinThresholdMock.sol
- test/mockContracts/VotingToChangeProxyAddressMock.sol
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
The `uint8` variables were changed to `uint256` to reduce gas spending.
(Fix)
> (Fix) Replace uint8 with uint256 to reduce gas spending

- contracts/BallotsStorage.sol
- contracts/EmissionFunds.sol
- contracts/KeysManager.sol
- contracts/RewardByBlock.sol
- contracts/ValidatorMetadata.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/VotingToManageEmissionFunds.sol
- contracts/interfaces/IBallotsStorage.sol
- scripts/migrate/migrateAll.js
- scripts/migrate/migrateKeys.js
- test/metadata_test.js
- test/metadata_upgrade_test.js
- test/voting_to_manage_emission_funds_test.js
- test/voting_to_manage_emission_funds_upgrade_test.js
Changes made within this PR:
- `tx.origin` was removed from the events of `EmissionFunds` contract;
- `this.` notation was removed from `KeysManager` and `VotingToChange*` contracts;
- `fullAddress` in `ValidatorMetadata` was limited to 200 bytes max;
- `VotingToManageEmissionFunds.previousBallotFinalized` function was renamed to `noActiveBallotExists`.
(Refactor)
> (Refactor) Remove `this` and other code improvements

- contracts/BallotsStorage.sol
- contracts/KeysManager.sol
- contracts/ProxyStorage.sol
- contracts/RewardByBlock.sol
- contracts/VotingToChangeKeys.sol
- contracts/VotingToChangeMinThreshold.sol
- contracts/VotingToChangeProxyAddress.sol
- contracts/VotingToManageEmissionFunds.sol
- contracts/interfaces/IBallotsStorage.sol
- contracts/interfaces/IProxyStorage.sol
- migrations/2_deploy_contract.js
- scripts/migrate/migrateAll.js
- test/proxy_storage_test.js
- test/proxy_storage_upgrade_test.js
- test/reward_by_block_test.js
- test/reward_by_block_upgrade_test.js
- test/voting_to_change_keys_test.js
- test/voting_to_change_keys_upgrade_test.js
- test/voting_to_change_min_threshold_test.js
- test/voting_to_change_min_threshold_upgrade_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
- test/voting_to_manage_emission_funds_test.js
- test/voting_to_manage_emission_funds_upgrade_test.js
The changes made within this PR:
1. `address` arguments have been put at the end of the argument list of several functions to limit the risk of `short address attack`:
- `BallotsStorage.areKeysBallotParamsValid`
- `BallotsStorage._areKeyAddingBallotParamsValid`
- `BallotsStorage._areKeyRemovalBallotParamsValid`
- `BallotsStorage._areKeySwapBallotParamsValid`
- `KeysManager._setInitialKeyStatus`
- `RewardByBlock.addExtraReceiver`
- `RewardByBlock._setExtraReceiverAmount`
- `VotingToChangeKeys.createBallot`
- `VotingToChangeKeys.createBallotToAddNewValidator`
- `VotingToChangeProxyAddress.createBallot`
- `VotingToManageEmissionFunds.init`
2. Checking of `msg.data.length` has been added to `KeysManager.checkIfMiningExisted` function.
3. `isValidator` function has …
> (Refactor) Put address arguments at the end of argument list of functions

- package.json
- scripts/checkForClashing.js
An introduction of the mechanism of upgradable contracts entails the risk of functions' signatures clashing in Proxy and underlying proxied contract. To exclude that risk the command `npm run test` was complemented with calling of `scripts/checkForClashing.js`. That's the script checking hashes of all functions of each contract for clashing with `EternalStorageProxy` contract's functions. See https://medium.com/nomic-labs-blog/malicious-backdoors-in-ethereum-proxies-62629adf3357 for more details.
(Feature)
> (Feature) Add script for checking contracts' functions for a clashing

- README.md
- make_flat.sh
- package-lock.json
- package.json
In order to simplify the setup of POA governance smart contracts, the proposal is to replace Python solidity flattener with [POA solidity-flattener](https://github.com/poanetwork/solidity-flattener). It [has no known vulnerabilities](https://snyk.io/test/github/poanetwork/solidity-flattener).
What does the simplification include:
- no need Python as a prerequisite
- no need solc binary a prerequisite (we have it as an npm package)
- no need to install Python solidity-flattener additionally (everything is installed from `npm install`)
> (Feature) POA solidity-flattener instead of Python solidity flattener

- contracts/RewardByBlock.sol
- migrations/2_deploy_contract.js
- test/reward_by_block_test.js
- test/reward_by_block_upgrade_test.js
Solves the issue https://github.com/poanetwork/poa-network-consensus-contracts/issues/186. Unit tests were also updated accordingly. These changes add the next public getters for reading minting statistics:
```
mintedForAccount(address _account) public view returns(uint256)
mintedForAccountInBlock(address _account, uint256 _blockNumber) public view returns(uint256)
mintedInBlock(uint256 _blockNumber) public view returns(uint256) public view returns(uint256)
mintedTotally() public view returns(uint256)
```
(Feature)
> (Feature) Add minting statistics to RewardByBlock contract

- migrations/2_deploy_contract.js
- package-lock.json
- package.json
This PR aims to get rid of uncontrolled structure for waiting of tx to create RewardByBlock contract and get its address:
- latest `web3@1.0` was added to dev dependencies
- async function `getRewardByBlockAddress` was added to get address of RewardByBlock contract
- `sleep` function was removed
> (Fix) Async wait for RewardByBlock contract address

- contracts/RewardByBlock.sol
- test/mockContracts/RewardByBlockMock.sol
- test/reward_by_block_test.js
- test/reward_by_block_upgrade_test.js
This PR solves the issue https://github.com/poanetwork/poa-network-consensus-contracts/issues/200. Now, `bridgesAllowed` function is used instead of `bridgeContract` constant. The new `mintedTotallyByBridge` function has been added to retrieve the total amount of coins minted by a specified bridge.
(Feature)
> (Feature) Allow using several bridges and add bridge minting statistics

- contracts/ProxyStorage.sol
- contracts/RewardByBlock.sol
- test/proxy_storage_test.js
- test/proxy_storage_upgrade_test.js
- test/voting_to_change_proxy_test.js
- test/voting_to_change_proxy_upgrade_test.js
This is an update of two contracts: `RewardByBlock` and `ProxyStorage`. The new implementation of `ProxyStorage` allows updating RewardByBlock's implementation through `voting to change proxy`. The new `RewardByBlock` returns empty arrays in case of zero input address for AuRa in `benefactors` array. This should help in solving the issue https://github.com/paritytech/parity-ethereum/issues/9764
(Fix)
> (Fix) Return empty results for zero input address in `RewardByBlock.reward` function
