poanetwork/poa-network-consensus-contracts

contracts/KeysManager.sol, package-lock.json, package.json, test/keys_manager_test.js, test/mockContracts/KeysManagerMock.sol, test/mockContracts/PoaNetworkConsensusMock.sol, test/poa_network_consensus_test.js
Implement KeysManager contract and cover it with tests for master of Ceremony and first 12 validators
=> Implement KeysManager contract 

contracts/ProxyStorage.sol, contracts/interfaces/IKeysManager.sol, test/ballots_storage_test.js, test/keys_manager_test.js
1. add a couple more tests
2. Remove public from variables in ProxyStorage
3. Remove private methods from KeysManager interface
=> Small optimization

Makefile, contracts/interfaces/IKeysManager.sol, migrations/2_deploy_contract.js, truffle.js
fix type in IKeysManager.sol interface for initialKeys
=> add deployment script

contracts/VotingToChangeKeys.sol, contracts/VotingToChangeMinThreshold.sol, contracts/VotingToChangeProxyAddress.sol, test/voting_to_change_keys_test.js, test/voting_to_change_min_threshold_test.js, test/voting_to_change_proxy_test.js
(Solution) Swap indexes when removing from an array
=> (Problem) Critical issue when finalizing a ballot it removes new ballot.

contracts/BallotsStorage.sol, contracts/KeysManager.sol, contracts/PoaNetworkConsensus.sol, contracts/VotingToChangeKeys.sol, contracts/VotingToChangeMinThreshold.sol, contracts/VotingToChangeProxyAddress.sol, contracts/interfaces/IKeysManager.sol, contracts/interfaces/IPoaNetworkConsensus.sol
(Solution) remove variables from interfaces and substitute them with getter functions
=> (Problem) Booky reported variable shadowing in interfaces.

README.md, package-lock.json, package.json
**Problem**: Travis and mochawesome links are outdated
**Solution**: Change links to match new organization name
=> Travis and mochawesome links with new organization name

README.md
=> (Fix) Audit links in README

contracts/VotingToChangeKeys.sol, contracts/VotingToChangeMinThreshold.sol, contracts/VotingToChangeProxyAddress.sol, test/voting_to_change_keys_test.js, test/voting_to_change_min_threshold_test.js, test/voting_to_change_proxy_test.js
Found a bug that you can't create ballot to swap voting and payout keys.
=> Hotfix -  fix swapping of payout and voting keys

README.md
Set of the tests are updated in README +16 tests
=> (Fix) Updated tests in README

contracts/KeysManager.sol, migrations/2_deploy_contract.js
Problem: 
POA is not deployed if it is used for HFs
=> (Feature) Update migrations to better deploy for HFs

scripts/getABI.js, scripts/package-lock.json, scripts/package.json
**Problem**: script generates ABIs to file with name like this `BallotsStorage.json.abi.json`
**Solution**: get base without extension for filename. Result: `BallotsStorage.abi.json`
=> (Fix) getABI.js script

contracts/ProxyStorage.sol
Increase a value of `contractVersion` variable in `ProxyStorage.sol`
(Fix)
=> (Fix, DEMO) Increase ProxyStorage version number

contracts/ProxyStorage.sol
Increase a value of `contractVersion` variable in `ProxyStorage.sol`
(Fix)
=> (Fix, MASTER) Increase ProxyStorage version number

scripts/package-lock.json, scripts/package.json
Updating `security-audit` branch with the latest changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/85.
(Fix)
=> (Fix) Update web3 in security-audit branch

contracts/BallotsStorage.sol, contracts/KeysManager.sol, contracts/PoaNetworkConsensus.sol, contracts/VotingToChangeKeys.sol, contracts/interfaces/IKeysManager.sol, test/ballots_storage_test.js, test/ballots_storage_upgrade_test.js, test/keys_manager_test.js, test/keys_manager_upgrade_test.js, test/mockContracts/KeysManagerMock.sol, test/poa_network_consensus_test.js, test/voting_to_change_keys_test.js, test/voting_to_change_keys_upgrade_test.js
Updating `security-audit` branch with the latest changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/100.
(Fix)
=> (Fix) MoC can be removed

contracts/KeysManager.sol, contracts/PoaNetworkConsensus.sol, contracts/ProxyStorage.sol, contracts/VotingToChangeKeys.sol, migrations/2_deploy_contract.js, package-lock.json, package.json, scripts/migrate/migrateAll.js, scripts/migrate/migrateKeys.js, test/ballots_storage_test.js, test/ballots_storage_upgrade_test.js, test/keys_manager_test.js, test/keys_manager_upgrade_test.js, test/metadata_test.js, test/metadata_upgrade_test.js, test/mockContracts/KeysManagerMock.sol, test/poa_network_consensus_test.js, test/voting_to_change_keys_test.js, test/voting_to_change_keys_upgrade_test.js, test/voting_to_change_min_threshold_test.js, test/voting_to_change_min_threshold_upgrade_test.js, test/voting_to_change_proxy_test.js, test/voting_to_change_proxy_upgrade_test.js
Updating `security-audit` branch with the latest changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/103 including a few enhancements.
(Fix)
=> (Fix) KeysManager and a few enhancements in security-audit branch

contracts/BlockReward.sol, contracts/EmissionFunds.sol, contracts/VotingToManageEmissionFunds.sol, test/block_reward_test.js, test/emission_funds_test.js, test/mockContracts/BlockRewardMock.sol, test/mockContracts/VotingToManageEmissionFundsMock.sol, test/upgradeContracts/VotingToManageEmissionFundsNew.sol, test/voting_to_manage_emission_funds_test.js, test/voting_to_manage_emission_funds_upgrade_test.js
Updating `security-audit` branch with the latest changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/86 and https://github.com/poanetwork/poa-network-consensus-contracts/issues/98.
(Feature)
=> (Feature) Unit tests and enhancements for Increased Emission Supply

README.md, contracts/VotingToChangeMinThreshold.sol, contracts/VotingToChangeProxyAddress.sol, contracts/abstracts/VotingToChange.sol, test/mockContracts/VotingToChangeMinThresholdMock.sol, test/voting_to_change_keys_test.js, test/voting_to_change_keys_upgrade_test.js, test/voting_to_change_min_threshold_test.js, test/voting_to_change_min_threshold_upgrade_test.js, test/voting_to_change_proxy_test.js, test/voting_to_change_proxy_upgrade_test.js
Changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/91 and https://github.com/poanetwork/RFC/issues/8.
(Feature)
=> (Feature) Allow finalize at once if all validators gave their votes

README.md, contracts/BallotsStorage.sol, contracts/KeysManager.sol, contracts/PoaNetworkConsensus.sol, contracts/VotingToChangeKeys.sol, contracts/VotingToManageEmissionFunds.sol, contracts/abstracts/VotingToChange.sol, contracts/interfaces/IBallotsStorage.sol, contracts/interfaces/IKeysManager.sol, contracts/interfaces/IPoaNetworkConsensus.sol, scripts/migrate/migrateAll.js, scripts/migrate/migrateKeys.js, test/ballots_storage_test.js, test/ballots_storage_upgrade_test.js, test/keys_manager_test.js, test/keys_manager_upgrade_test.js, test/poa_network_consensus_test.js, test/voting_to_change_keys_test.js, test/voting_to_change_keys_upgrade_test.js
Changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/115, https://github.com/poanetwork/poa-network-consensus-contracts/issues/116, https://github.com/poanetwork/poa-network-consensus-contracts/issues/117, https://github.com/poanetwork/poa-network-consensus-contracts/issues/119, https://github.com/poanetwork/poa-network-consensus-contracts/issues/120 and https://github.com/poanetwork/poa-network-consensus-contracts/issues/121.
(Refactor)
=> (Refactor) Small enhancements, refactoring and fixes

contracts/PoaNetworkConsensus.sol, migrations/2_deploy_contract.js, scripts/migrate/migrateAll.js, scripts/migrate/migrateMetadata.js, scripts/migrate/migrateMetadataNew.js, test/keys_manager_test.js, test/keys_manager_upgrade_test.js, test/mockContracts/PoaNetworkConsensusMock.sol, test/poa_network_consensus_test.js, test/voting_to_change_keys_test.js, test/voting_to_change_keys_upgrade_test.js, truffle.js
Changes related to https://github.com/poanetwork/poa-network-consensus-contracts/issues/57.
(Fix)
=> (Fix) PoaNetworkConsensus small changes

migrations/2_deploy_contract.js, truffle.js
The `migrations/2_deploy_contract.js` script doesn't work with new `truffle 4.1.11`. This PR fixes it.
(Fix)
=> (Fix) migrations/2_deploy_contract.js

contracts/KeysManager.sol, test/keys_manager_test.js, test/keys_manager_upgrade_test.js
Changes related to #126.
(Fix)
=> (Fix) removeVotingKey and removePayoutKey shouldn't revert if voting/ payout key is already removed

scripts/migrate/utils/utils.js
This small PR adds checking of each transaction's status using the field `status` returned by `web3.eth.sendSignedTransaction` function in `scripts/migrate/utils/utils.js`.
(Fix)
=> (Fix) Checking transaction status in scripts/migrate

migrations/2_deploy_contract.js, truffle.js
`migrations/2_deploy_contract.js` script has been rewritten to use async/ await instead of promises.
(Refactor)
=> (Refactor) Rewrite migrations/2_deploy_contract.js

contracts/BlockReward.sol, test/block_reward_test.js
The name of `rewardHBBFT` function has been changed to `rewardByTime` in `BlockReward` contract.
(Refactor)
=> (Refactor) Rename BlockReward.rewardHBBFT function to rewardByTime

scripts/package-lock.json, scripts/package.json
Adds `solc` to `scripts/package.json` according to https://github.com/poanetwork/poa-network-consensus-contracts/issues/137.
(Fix)
=> (Fix) Add solc to scripts/package.json

scripts/migrate/migrateAll.js, scripts/migrate/migrateKeys.js, scripts/migrate/migrateMetadataNew.js, scripts/migrate/migrateVotings.js
URLs were fixed in `scripts/migrate/migrate*.js` for Web3 HttpProvider.
(Fix)
=> (Fix) scripts/migrate/migrate*.js

scripts/migrate/migrateAll.js, scripts/migrate/utils/utils.js
URL for Web3 HttpProvider was fixed in `scripts/migrate/utils/utils.js`.
(Fix)
=> (Fix) scripts/migrate/utils/utils.js

contracts/RewardByBlock.sol, contracts/interfaces/IProxyStorage.sol, test/mockContracts/RewardByBlockMock.sol, test/reward_by_block_test.js, test/reward_by_block_upgrade_test.js
`RewardByBlock` contract was supplemented by `addExtraReceiver` function (with corresponding unit tests) for the logic described in https://github.com/poanetwork/RFC/issues/22. 
(Feature)
=> (Feature) A new RewardByBlock.addExtraReceiver function

contracts/BallotsStorage.sol, contracts/PoaNetworkConsensus.sol, contracts/ValidatorMetadata.sol, contracts/VotingToChangeMinThreshold.sol, contracts/abstracts/ThresholdTypesEnum.sol, contracts/abstracts/VotingTo.sol, test/poa_network_consensus_test.js
This PR implements a few refactoring proposals by MixBytes audit team.
(Refactor)
=> (Refactor) A few enhancements proposed by auditors

contracts/KeysManager.sol, contracts/VotingToChangeKeys.sol, test/ballots_storage_test.js, test/ballots_storage_upgrade_test.js, test/emission_funds_test.js, test/keys_manager_test.js, test/keys_manager_upgrade_test.js, test/metadata_test.js, test/metadata_upgrade_test.js, test/poa_network_consensus_test.js, test/proxy_storage_test.js, test/proxy_storage_upgrade_test.js, test/reward_by_block_test.js, test/reward_by_block_upgrade_test.js, test/reward_by_time_test.js, test/reward_by_time_upgrade_test.js, test/voting_to_change_keys_test.js, test/voting_to_change_keys_upgrade_test.js, test/voting_to_change_min_threshold_test.js, test/voting_to_change_min_threshold_upgrade_test.js, test/voting_to_change_proxy_test.js, test/voting_to_change_proxy_upgrade_test.js, test/voting_to_manage_emission_funds_test.js, test/voting_to_manage_emission_funds_upgrade_test.js
This PR implements a few enhancements proposed by MixBytes audit team.
(Fix)
=> (Fix) KeysManager, VotingToChangeKeys and unit tests enhancements

contracts/VotingToChangeKeys.sol, contracts/VotingToChangeMinThreshold.sol, contracts/VotingToChangeProxyAddress.sol, contracts/abstracts/VotingTo.sol, contracts/abstracts/VotingToChange.sol, contracts/eternal-storage/EternalStorageProxy.sol, contracts/interfaces/IVotingToChangeKeysPrev.sol, contracts/interfaces/IVotingToChangeMinThresholdPrev.sol, contracts/interfaces/IVotingToChangePrev.sol, contracts/interfaces/IVotingToChangeProxyAddressPrev.sol, package-lock.json, scripts/migrate/migrateAll.js, scripts/package-lock.json, test/mockContracts/RewardByBlockMock.sol
Removes theoretical reentrancy from `VotingTo._createBallot` function. Removes `payable` keyword from `EternalStorageProxy` contract. Removes excess interfaces for `VotingTo*` contracts. Fixes replacement the address of `EmissionFunds` contract in `scripts/migrate/migrateAll.js` script.
(Fix)
=> (Fix) Remove theoretical reentrancy from `VotingTo._createBallot` method and other enhancements

contracts/BallotsStorage.sol, contracts/KeysManager.sol, contracts/RewardByBlock.sol, contracts/ValidatorMetadata.sol, contracts/VotingToChangeKeys.sol, contracts/VotingToChangeMinThreshold.sol, contracts/VotingToChangeProxyAddress.sol, contracts/VotingToManageEmissionFunds.sol, contracts/abstracts/VotingTo.sol, contracts/abstracts/VotingToChange.sol, contracts/eternal-storage/EternalStorageProxy.sol, scripts/getDeployEstimateGas.js, scripts/migrate/migrateAll.js, scripts/migrate/migrateKeys.js, scripts/migrate/migrateVotings.js, scripts/migrate/utils/utils.js
Changes made:
- all `string` constants were changed to `bytes32` constants to save a significant amount of gas for deployment;
- assigning to function's parameters was removed for some functions;
- `IEternalStorageProxy` interface is now explicitly implemented;
- `scripts/getDeployEstimateGas.js` script was improved to take into account the `EternalStorageProxy` contract;
- migration scripts in `scripts/migrate` directory were improved to handle possible exceptions and to be able to make repeated tries.
(Fix)
=> (Fix) Reduce gas spending, improve migrations, and minor enhancements

contracts/VotingToManageEmissionFunds.sol
The code of `VotingToManageEmissionFunds._finalize` was simplified.
(Fix)
=> (Fix) Enhancement of VotingToManageEmissionFunds._finalize function

migrations/2_deploy_contract.js, scripts/migrate/migrateAll.js, scripts/migrate/migrateVotings.js, scripts/migrate/package-lock.json
Minor changes of deploy and migration scripts for the second hard fork in `Core` network. Should be merged after https://github.com/poanetwork/poa-network-consensus-contracts/pull/201 is merged.
(Fix)
=> (Fix) Prepare to HF2 in Core

contracts/ValidatorMetadata.sol, package-lock.json, scripts/checkForClashing.js, test/keys_manager_test.js, test/keys_manager_upgrade_test.js, test/metadata_test.js, test/metadata_upgrade_test.js
These changes add two new fields into `ValidatorMetadata` contract according to https://github.com/poanetwork/poa-dapps-validators/issues/96: `contactEmail` (bytes32) and `isCompany` (bool).
(Feature)
=> (Feature) Add fields into ValidatorMetadata for companies as validators
